---
title: Iteration and Flow Control
subtitle: 'Part 3: Essential Concepts for New Python Users'
description: Overview of iteration and flow control in Python.
slug: iteration-and-flow-control
tags:
- python
- beginners
- jupyter
- syntax
---

Welcome to iteration and flow controls! Looping and logic determine what code runs and when. These concepts are the core to creating maintainable and versatile code. Be sure to check out the accompanying notebook for more experience.

**NOTE**: By design, Python does not return anything when a variable is assigned. So example cells here, where only variable assignment happens, will run without generating output. The variable is still saved in the runtime and can be accessed in following cells once it is set.

::: {.callout icon="none" .custom-callout .best-practice title="DRY - Don't Repeat Yourself"}

DRY, a principle of software engineering, reminds developers to avoid duplicative or repetitive code. Having multiple code sections that are nearly identical is a pain to maintain. If you ever find yourself having to edit code in multiple places for a single change, consider if there is a better approach. Iteration and flow control are core ways to ensure DRY code.
:::


## Iteration

Many datatypes allow for iteration. This section will focus on lists, strings, ranges, and dictionaries as examples. Iteration repeatedly executes a block of code.

### Lists

List iteration is incredibly powerful. The cells below first create a list, then iterates over it.
```{pyodide-python}
names_list = ['Amanda', 'John', 'Paul', 'Junior', 'Emily']
```
```{pyodide-python}
for name in names_list:
	print(name)
```
```{pyodide-python}
for name in names_list:
	print(name + ' is jumping into Python!')
```

### Strings

Stings in Python are iterable. See the below to iterate over characters.
```{pyodide-python}
python_string = 'Python'
```
```{pyodide-python}
for letter in python_string:
	print(letter)
```

#### Nested Loops

Loops can be nested.
```{pyodide-python}
for name in names_list:
	for letter in name:
		print(letter)
```

### Ranges

Range can be used to execute code a given number of times. Usage is `range(start, stop, step)`, where stop is required and start and step are optional. Stop is exclusive, meaning that number is not part of the sequence. Examples below help illustrate. **NOTE:** Python is a `0` based indexing system.
```{pyodide-python}
for i in range(5):
	print(i)
```
```{pyodide-python}
for i in range(1, 5):
	print(i)
```
```{pyodide-python}
for i in range(1, 10, 3):
	print(i)
```

#### Enumerate

Enumerate is a built-in function to add a counter to iteratable objects like lists.
```{pyodide-python}
for i, name in enumerate(names_list):
	print(str(i) + ' - ' + name)
```

### Dictionaries

Dictionaries hold mapped key-value pairs. They are iterable, but must be handled differently than lists. `keys` will iterate over the keys, while `values` iterates over the values, and `items` iterates over both.
```{pyodide-python}
my_dict = {'a': 0, 'b': 1, 'c': 2}
```
```{pyodide-python}
for k in my_dict.keys():
	print(k)
```
```{pyodide-python}
for v in my_dict.values():
	print(v)
```
```{pyodide-python}
for k, v in my_dict.items():
	print(k + ' - ' + str(v))
```

#### Dictionary Lookup

Dictionary mapping is usefulf in many contexts. The key of a dictionary can be used to lookup the corresponding value. 

Syntax: `dict[key]`.
```{pyodide-python}
for k in my_dict.keys():
	print(my_dict[k])
```

## Flow Control

By default, code is executed from the top to bottom of a script. Flow control is used for more advanced execution that may include repeating blocks, skipping conditions, early exits, and error handling. The 'if-elif-else' conditional statement is the most commonly used method of flow control in Python.

When combined with iteration and DRY, very little code can have very impactful results.

### If-Elif-Else

The most commonly used flow control in Python. Run the cells below and edit to make x the magic number.
```{pyodide-python}
x = 28
if x == 23:
	print('The magic number!')
elif x > 23:
	print('This number is too big...')
else:
	print('This number is too small')
```

#### Iteration and Flow
```{pyodide-python}
for name in names_list:
	if 'a' in name:
		print(name)
```
```{pyodide-python}
for i, name in enumerate(names_list):
	if i > 2:
		print(name)
```

### Next Steps

Keep going with [errors and experimentation  →](/foundations/try-python/errors-experimentation.qmd).