---
title: Jump In
subtitle: Code Freely <span class="subtitle-divider">|</span> Fail Safely <span class="subtitle-divider">|</span>
  Start Quickly
description: "Learn programming basics without setup or headaches. Interactive tools\
  \ let you explore data types, operators, flow control, and more \u2014 all in your\
  \ browser."
navdesc: Experiment and see if Python works for you
format:
  html:
    page-layout: full
    toc: false
    title-block-banner: true
slug: jump-in
---

Jump into Python with hands-on practice, right in your browser. No installations, no setups, no signin. These pages use embedded code blocks to edit and run code. For extra experience, check out the notebooks too!

**Try, test, and tinker — it's all part of the process.**

::: {.callout icon="none" .custom-callout .pxp-ref title="Interactive Pages and Notebooks"}

Jump In includes both interative pages and notebooks.

**Pages** take a moment to load-an indicator at the top of page monitors the status. Interactive cells can be edited and feature a `Run Code` button that will generate the output below. Use these cells to test your understanding and explore coding concepts. Refreshing or leaving the page will remove all edits.

**Notebooks** open in a new tab and run using JupyterLite. See the [Jupyter Notebook](/getting-started/jupyter-notebooks.qmd) page, if you're unfamiliar. Exiting the page will remove all edits, so be sure to download work you want to save.

Start with the pages and then test yourself with notebooks. This is a great place to learn by doing!
:::


## Content Guide

Built to explore, all notebooks in this section are **interactive** - no setup required. Content overviews are paired with notebooks to improve learning and encourage testing. Several skill test notebooks are also included to cement what you learn.

Ready to push your skills? Use the **notebook challenges** to reinforce these concepts with more hands-on practice. Be sure to save a copy of any work you want to keep!

<hr class="page-divider">

<div class="table-cheatsheet">
| Topic | Page | Notebook | Interactive Notebook | Download |
| --- | --- | --- | --- | --- |
| Datatypes and Operators | {{< fa regular window-maximize >}} [Interactive Page](/jump-in/datatypes-and-operators.qmd) | {{< fa regular rectangle-list >}} [Notebook](/jump-in/notebooks/datatypes-and-operators-nb.ipynb) | {{< fa regular file-code >}} [Interactive Notebook](/jump-in/jl-notebooks/jl-build/tree/index.html?path=datatypes-and-operators-nb-jp.ipynb){target="_blank"} | <a href="/jump-in/jl-notebooks/files/datatypes-and-operators-nb-jp.ipynb" download>📥 Download </a> |
| Variables and Functions | {{< fa regular window-maximize >}} [Interactive Page](/jump-in/variables-and-functions.qmd) | {{< fa regular rectangle-list >}} [Notebook](/jump-in/notebooks/variables-and-functions-nb.ipynb) | {{< fa regular file-code >}} [Interactive Notebook](/jump-in/jl-notebooks/jl-build/tree/index.html?path=variables-and-functions-nb-jp.ipynb){target="_blank"} | <a href="/jump-in/jl-notebooks/files/variables-and-functions-nb-jp.ipynb" download>📥 Download </a> |
| Iteration and Flow Control | {{< fa regular window-maximize >}} [Interactive Page](/jump-in/iteration-and-flow-control.qmd) | {{< fa regular rectangle-list >}} [Notebook](/jump-in/notebooks/iteration-and-flow-control-nb.ipynb) | {{< fa regular file-code >}} [Interactive Notebook](/jump-in/jl-notebooks/jl-build/tree/index.html?path=iteration-and-flow-control-nb-jp.ipynb){target="_blank"} | <a href="/jump-in/jl-notebooks/files/iteration-and-flow-control-nb-jp.ipynb" download>📥 Download </a> |
| Errors and Experimentation | {{< fa regular window-maximize >}} [Interactive Page](/jump-in/errors-and-experimentation.qmd) | {{< fa regular rectangle-list >}} [Notebook](/jump-in/notebooks/errors-and-experimentation-nb.ipynb) | {{< fa regular file-code >}} [Interactive Notebook](/jump-in/jl-notebooks/jl-build/tree/index.html?path=errors-and-experimentation-nb-jp.ipynb){target="_blank"} | <a href="/jump-in/jl-notebooks/files/errors-and-experimentation-nb-jp.ipynb" download>📥 Download </a> |
| Hello World | Notebook only challenge! | {{< fa regular rectangle-list >}} [Notebook](/jump-in/notebooks/hello-world-challenge-nb.ipynb) | {{< fa regular file-code >}} [Interactive Notebook](/jump-in/jl-notebooks/jl-build/tree/index.html?path=hello-world-challenge-nb-jp.ipynb){target="_blank"} | <a href="/jump-in/jl-notebooks/files/hello-world-challenge-nb-jp.ipynb" download>📥 Download </a> |
| Expert Debugger | Notebook only challenge! | {{< fa regular rectangle-list >}} [Notebook](/jump-in/notebooks/hello-world-challenge-nb.ipynb) | {{< fa regular file-code >}} [Interactive Notebook](/jump-in/jl-notebooks/jl-build/tree/index.html?path=expert-debugger-challenge-nb-jp.ipynb){target="_blank"} | <a href="/jump-in/jl-notebooks/files/expert-debugger-challenge-nb-jp.ipynb" download>📥 Download </a> |

</div>


<hr class="page-divider">

::: {.callout icon="none" .custom-callout .d-bugz title="Experience from Errors"}

These bugs don't bite! Writing a complex program without errors is as probable as writing a novel without a typo. The key is test for errors, ensure things work properly, and address the issues. Understanding basic errors will allow you tackle much more complex tasks.

**Code Freely** — programming is interactive, so try things, test things, experiment

**Fail Safely** — mistakes don't hurt here, if something goes wrong simply reset the workspace

**Start Quickly** — examine inputs and outputs, read error messages, iterate and experiment if unsure
:::


<div class="page-quote">
Hands on is the only true way to learn programming
</div>


Start small. Make mistakes. Fix errors. This is a space to experiment freely, play around, and learn by doing. Nothing to break here, no risks, consider this a playground for learning. **Jump in!**
