---
title: Variables and Functions
subtitle: 'Part 2: Essential Concepts for New Python Users'
description: Overview of variables and functions in Python.
slug: variables-and-functions
tags:
- python
- beginners
- jupyter
- syntax
---

## Get Started with Python - Part 2

This is the second part of the `Jump In` guide introducing core Python concepts in a hands-on way, using **Jupyter notebooks** as the primary environment. This page will cover variables and built-in functions. Be sure to check out the accompanying notebook for more hands-on experience.

::: {.callout icon="none" .custom-callout .best-practice title="Reusability"}

Effective programming is built around reusability. Creating automated, reproducible code starts with variables and functions.
:::


## Variables

Variable assignment stores data in a named container. In Python, use `=` to assign values: `x = 5`. Variables are case-sensitive and can store numbers, strings, lists, and other datatypes. Variables in Python are **mutable** meaning the value can be modified.

<div class="table-cheatsheet">
| Example | Valid? | Reason |
| --- | --- | --- |
| age = 25 | ✅ Yes | Starts with a letter, letters only |
| user_name = "A" | ✅ Yes | Letters + underscore are allowed |
| temperature2 | ✅ Yes | Digits allowed, but not at start |
| _hidden | ✅ Yes | Leading underscore allowed (often used for “private” values) |
| MAX_VALUE | ✅ Yes | Uppercase is allowed, often used for constants |
| 2nd_value | ❌ No | Cannot start with a digit |
| user-name | ❌ No | Dash (-) not allowed |
| file.path | ❌ No | Dot (.) means “attribute,” not part of a name |
| my var | ❌ No | Spaces not allowed |
| return = 5 | ❌ No | return is a reserved Python keyword |

</div>


## Functions

Functions create reusable code which can simplify tasks, allow iterative runs, and can make your code **much** more powerful. Python comes with some [builtin functions](https://docs.python.org/3/library/functions.html) which will help demonstrate. The table below outlines so of the most commonly used ones and their usage.

<div class="table-cheatsheet">
| Function | Example | Meaning | Result |
| --- | --- | --- | --- |
| help | help(len) | Displays documentation about an object or function | Shows usage info in console |
| len | len([1, 2, 3]) | Returns the number of items in an object | 3 |
| print | print('Hello') | Outputs text or variables to the console | Hello |
| type | type(3.14) | Returns the data type of an object | <class 'float'> |
| min | min(4, 7, 2) | Returns the smallest of the given values | 2 |
| max | max(4, 7, 2) | Returns the largest of the given values | 7 |
| str | str(123) | Converts a value to a string | '123' |
| int | int(3.9) | Converts a value to an integer (truncates decimals) | 3 |
| float | float('3.14') | Converts a value to a floating-point number | 3.14 |

</div>

